export const ASYNC_UPDATE_COMPANY = "ASYNC_UPDATE_COMPANY";
export const ASYNC_UPDATE_COMPANY_SUCCESS = "ASYNC_UPDATE_COMPANY_SUCCESS";
export const ASYNC_UPDATE_COMPANY_FAILED = "ASYNC_UPDATE_COMPANY_FAILED";

export const ASYNC_GET_COMPANY_DETAILS = "ASYNC_GET_COMPANY_DETAILS";
export const ASYNC_GET_COMPANY_DETAILS_SUCCESS = "ASYNC_GET_COMPANY_DETAILS_SUCCESS";
export const ASYNC_GET_COMPANY_DETAILS_FAILED = "ASYNC_GET_COMPANY_DETAILS_FAILED";

export const updateCompany = (payload: any) => ({
  type: ASYNC_UPDATE_COMPANY,
  payload,
});

export const getCompanyDetails = (companyId: any) => ({
  type: ASYNC_GET_COMPANY_DETAILS,
  payload: companyId,
});
