export const ASYNC_GET_QUOTATIONS = 'ASYNC_GET_QUOTATIONS';
export const ASYNC_GET_QUOTATIONS_SUCCESS = 'ASYNC_GET_QUOTATIONS_SUCCESS';
export const ASYNC_GET_QUOTATIONS_FAILED = 'ASYNC_GET_QUOTATIONS_FAILED';

export const ASYNC_GET_QUOTATION_DETAILS = 'ASYNC_GET_QUOTATION_DETAILS';
export const ASYNC_GET_QUOTATION_DETAILS_SUCCESS = 'ASYNC_GET_QUOTATION_DETAILS_SUCCESS';
export const ASYNC_GET_QUOTATION_DETAILS_FAILED = 'ASYNC_GET_QUOTATION_DETAILS_FAILED';

export const ASYNC_GET_QUOTATION_HISTORY = 'ASYNC_GET_QUOTATION_HISTORY';
export const ASYNC_GET_QUOTATION_HISTORY_SUCCESS = 'ASYNC_GET_QUOTATION_HISTORY_SUCCESS';
export const ASYNC_GET_QUOTATION_HISTORY_FAILED = 'ASYNC_GET_QUOTATION_HISTORY_FAILED';

export const ASYNC_GET_QUOTATION_TIMELINE = 'ASYNC_GET_QUOTATION_TIMELINE';
export const ASYNC_GET_QUOTATION_TIMELINE_SUCCESS = 'ASYNC_GET_QUOTATION_TIMELINE_SUCCESS';
export const ASYNC_GET_QUOTATION_TIMELINE_FAILED = 'ASYNC_GET_QUOTATION_TIMELINE_FAILED';

export const ASYNC_SEND_QUOTATION = 'ASYNC_SEND_QUOTATION';
export const ASYNC_SEND_QUOTATION_SUCCESS = 'ASYNC_SEND_QUOTATION_SUCCESS';
export const ASYNC_SEND_QUOTATION_FAILED = 'ASYNC_SEND_QUOTATION_FAILED';

export const ASYNC_APPROVE_QUOTATION = 'ASYNC_APPROVE_QUOTATION';
export const ASYNC_APPROVE_QUOTATION_SUCCESS = 'ASYNC_APPROVE_QUOTATION_SUCCESS';
export const ASYNC_APPROVE_QUOTATION_FAILED = 'ASYNC_APPROVE_QUOTATION_FAILED';

export const ASYNC_CREATE_QUOTATION = 'ASYNC_CREATE_QUOTATION';
export const ASYNC_CREATE_QUOTATION_SUCCESS = 'ASYNC_CREATE_QUOTATION_SUCCESS';
export const ASYNC_CREATE_QUOTATION_FAILED = 'ASYNC_CREATE_QUOTATION_FAILED';

export const ASYNC_UPDATE_QUOTATION = 'ASYNC_UPDATE_QUOTATION';
export const ASYNC_UPDATE_QUOTATION_SUCCESS = 'ASYNC_UPDATE_QUOTATION_SUCCESS';
export const ASYNC_UPDATE_QUOTATION_FAILED = 'ASYNC_UPDATE_QUOTATION_FAILED';

export const ASYNC_DELETE_QUOTATION = 'ASYNC_DELETE_QUOTATION';
export const ASYNC_DELETE_QUOTATION_SUCCESS = 'ASYNC_DELETE_QUOTATION_SUCCESS';
export const ASYNC_DELETE_QUOTATION_FAILED = 'ASYNC_DELETE_QUOTATION_FAILED';

export const getQuotations = (payload: any) => ({
  type: ASYNC_GET_QUOTATIONS,
  payload,
});

export const getQuotationDetails = (payload: any) => ({
  type: ASYNC_GET_QUOTATION_DETAILS,
  payload,
});

export const getQuotationHistory = (payload: any) => ({
  type: ASYNC_GET_QUOTATION_HISTORY,
  payload,
});

export const getQuotationTimeline = (payload: any) => ({
  type: ASYNC_GET_QUOTATION_TIMELINE,
  payload,
});

export const sendQuotation = (payload: any) => ({
  type: ASYNC_SEND_QUOTATION,
  payload,
});

export const approveQuotation = (payload: any) => ({
  type: ASYNC_APPROVE_QUOTATION,
  payload,
});

export const createQuotation = (payload: any) => ({
  type: ASYNC_CREATE_QUOTATION,
  payload,
});

export const updateQuotation = (payload: any) => ({
  type: ASYNC_UPDATE_QUOTATION,
  payload,
});

export const deleteQuotation = (payload: any) => ({
  type: ASYNC_DELETE_QUOTATION,
  payload,
});
